[package]
name = "xtask"
version = "0.4.0"
edition = "2018"
publish = false

[dependencies]
structopt = "0.3"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
once_cell = "1.8"
chrono = { version = "0.4", features = ["serde"] }
zip = "0.6"
regex = "1.5"
array_tool = "1.0.3"
dialoguer = "0.10"
flate2 = "1.0"
globset = "~0.4"
Inflector = "0.11.4"
indicatif = "0.17.3"
itertools = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.8"
path-slash = "0.2.1"
quote = "~0.3"
reduce = "0.1.2"
semver = "1.0"
simple_logger = "4.0.0"
syn = { version = "~0.11", features = ["full"] }
tar = "0.4"
toml = "0.5"
url = "2.1"
void = "1.0"


[dev-dependencies]
tempfile = "3.1.0"
